# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hydeweb"
  s.version = "0.1.0.pre1"
  s.summary = "Website preprocessor."
  s.description = "Hyde lets you create static websites from a bunch of files written in HAML, Textile, Sass, or any other."
  s.authors = ["Rico Sta. Cruz"]
  s.email = ["rico@sinefunc.com"]
  s.homepage = "http://github.com/sinefunc/hyde"
  s.files = ["bin/nhyde", "lib/hyde", "lib/hyde/cli", "lib/hyde/cli/helpers.rb", "lib/hyde/cli.rb", "lib/hyde/config.rb", "lib/hyde/helpers.rb", "lib/hyde/layout.rb", "lib/hyde/page.rb", "lib/hyde/partial.rb", "lib/hyde/project.rb", "lib/hyde/server.rb", "lib/hyde.rb", "test/fixture", "test/fixture/extensions", "test/fixture/extensions/extensions", "test/fixture/extensions/extensions/a", "test/fixture/extensions/extensions/a/a.rb", "test/fixture/extensions/hyde.conf", "test/fixture/extensions/site", "test/fixture/extensions/site/index.haml", "test/fixture/one", "test/fixture/one/control", "test/fixture/one/control/about", "test/fixture/one/control/about/index.css", "test/fixture/one/control/cheers.html", "test/fixture/one/control/css", "test/fixture/one/control/css/style.css", "test/fixture/one/control/hello.html", "test/fixture/one/control/hi.html", "test/fixture/one/control/index.html", "test/fixture/one/hyde.conf", "test/fixture/one/layouts", "test/fixture/one/layouts/default.haml", "test/fixture/one/partials", "test/fixture/one/partials/menu.haml", "test/fixture/one/site", "test/fixture/one/site/about", "test/fixture/one/site/about/index.scss", "test/fixture/one/site/cheers.html.haml", "test/fixture/one/site/css", "test/fixture/one/site/css/style.scss", "test/fixture/one/site/hello.haml", "test/fixture/one/site/hi.html", "test/fixture/one/site/index.haml", "test/helper.rb", "test/unit", "test/unit/extensions_test.rb", "test/unit/fixture_test.rb", "test/unit/hyde_test.rb", "TODO.md", "Rakefile"]
  s.executables = ["nhyde"]

  s.add_development_dependency "haml"
  s.add_development_dependency "less"
  s.add_development_dependency "maruku"
end

